### ISSUE TITLE
Docker hub not building latest 4.9.x ??

### ISSUE THREAD

**Issue by timwsuqld** [phpmyadmin/docker#228]
Not sure why, but Docker Hub hasn't built the latest 4.9 images. Maybe an issue with Github/Docker Hub integration? Or just a missing 4.9.0.1 tag?

**Comment by williamdes** [comment]
@timwsuqld It would be done soon, I messaged @ibennetch about that :)

**Comment by ibennetch** [comment]
Thanks for reporting this!

This is a little complicated to resolve. It relates to #200 which removed `Dockerfile` in favor of more specific files for various webservers and PHP integrations. Our current workflow happens to only build off a `./Dockerfile` so I have to do a little work to fix our release process. This probably is the same cause as #227.

**Comment by ibennetch** [comment]
I've gotten the Docker images updated. These tags are currently available, now including a few new ones:

* `4.9` - the most recent stable phpMyAdmin 4.9.x version, currently 4.9.1
* `edge` - stable phpMyAdmin (currently 4.9.1)
* `latest` - Similar to `edge`, has stable phpMyAdmin with somewhat more stable Dockerfile
* `edge-4.9` - Latest 4.9.x development snapshot (from QA_4_9)
* `fpm` - stable version, see #200 for details
* `fpm-alpine` - stable version, see #200 for details

Note that these tags may change in the near future as we try to adjust our offerings as we learn better ways to standardize this process and roll out more consistent naming of the newer fpm/fpm-alpine releases.

**Comment by deeky666** [comment]
@ibennetch is there a reason why there are no tags for releases like `4.9.0.1`, `4.9.1` etc. for `4.9` branch?

**Comment by ibennetch** [comment]
@deeky666 This should be fixed now, there should be a 4.9.2 tag for the release I published yesterday. There's still a manual step that I missed with 4.9.0.1 and 4.9.1, my mistake. Thanks for pointing this out.

**Comment by deeky666** [comment]
@ibennetch thanks for looking into this. Unfortunately I still don't see any of those tags on Docker Hub:

![grafik](https://user-images.githubusercontent.com/1411514/69527508-bb363d00-0f6c-11ea-98a7-6b400fdcad65.png)

**Comment by williamdes** [comment]
#256

**Comment by ibennetch** [comment]
I was incorrect with [my response](https://github.com/phpmyadmin/docker/issues/228#issuecomment-557800320) above about the 4.9.0.1 and 4.9.2 tags; I realized that the '4.9' tag hadn't updated and, when I came back to comment, responded to the wrong question.

So the Docker hub builds are (as far as I can tell) working correctly for the tags we currently advertise. Further discussion about the 'patch version' tags can occur in the issue https://github.com/phpmyadmin/docker/issues/256.
