### ISSUE TITLE
Cannot connect to MySQL - getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by RickD123** [phpmyadmin/docker#273]
Hi,

I am trying to make use of a dockerized PHPmyadmin and I am having some difficulties. Specifically, I cannot resolve the name of the MySQL container to connect to it. Here is my docker-compose.yml:

```yml
version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /srv/my.domain.tld/htdocs:/srv/www/my.domain.tld/htdocs
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    depends_on:
        - php

  php:
    image: php:7-fpm
    container_name: php
    ports:
     - "127.0.0.1:9000:9000"
    volumes:
     - /srv/www/my.domain.tld/htdocs:/srv/www/my.domain.tld/htdocs
    depends_on:
     - mysql

  mysql:
        image: mysql:5.7.21
        container_name: mysql
        restart: always
        ports:
            - "127.0.0.1:3306:3306"
        command:
        - mysqld
        - --default-authentication-plugin=mysql_native_password
        - --default_storage_engine=InnoDB
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        - --init-connect=SET NAMES utf8
        - --innodb_log_file_size=256M
        - --innodb_buffer_pool_size=3GB
        - --max_allowed_packet=20M
        - --bulk_insert_buffer_size=20M
        - --query_cache_size=32M
        - --skip-character-set-client-handshake
        - --skip-host-cache
        - --wait_timeout=600
        volumes:
         - ./conf:/etc/mysql/conf.d
         - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
     - PMA_HOST = mysql
     - PMA_PORT = 3306
     - PMA_ABSOLUTE_URI = https://my.domain.tld/phpmyadmin/
    volumes:
      - phpmyadmin_data:/var/www/html/
    ports:
     - "127.0.0.1:8000:80"
    links:
     - mysql

volumes:
    persistent: 
    phpmyadmin_data:

```

As you can see I have the "PMA_HOST" defined (I also tried with IP address), but I am getting the following error message when trying to log into PHPMyAdmin:

mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known
   mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known

Any ideas on how this can be fixed? When using PMA_ARBITRARY and then entering "mysql" as host, I am getting an error message that the docker default container is not allowed to connect to the MySQL DB, meaning it seems to understand "mysql" as DB host. 

Kind regards
RickD

**Comment by williamdes** [comment]
Hi @RickD123 

You reported 2 errors:
- for the getaddrinfo error it seems solved with `PMA_HOST = mysql` right?
- "I am getting an error message that the docker default container is not allowed to connect to the MySQL DB" did you check the privileges ? is it a new server or did you create it ?

**Comment by RickD123** [comment]
Hi, 

sorry @williamdes my bug report was a bit misleading, apologies. I wanted to discuss the first issues which is not fixed. Setting "PMA_HOST=mysql" still results in the same getaddrinfo error in PHPMyAdmin. The second issue I can fix myself with the MySQL access rights system. Any ideas what might be causing issue 1? Can you reproduce this?

Many thanks.

Kind regards
RickD

**Comment by williamdes** [comment]
I think you should try network option like I did in https://github.com/wdesportes/phpmyadmin-local-setup/blob/master/docker-compose-pma.yml

**Comment by RickD123** [comment]
Works like a charm, thanks a lot!
