### ISSUE TITLE
Frequently losing session

### ISSUE THREAD

**Issue by DavidMaza** [phpmyadmin/docker#32]
I have a fairly vanilla version of the phpMyAdmin docker container yet after I login, I keep losing the session and are taken back to the login screen. Sometimes it'll happen after a few seconds, sometimes after a minute or two.

I've tried clearing all the cookies in my browser, tried multiple computers and multiple browsers without much luck.

Below is the Docker command being used to start the container:

```
docker run \
		--name phpMyAdmin \
		--restart=always \
		-d \
		-p 8080:80 \
		--link mysql:db \
		phpmyadmin/phpmyadmin
```

**Comment by nijel** [comment]
Can you see if the container is restarted when you loose the session?

See also https://github.com/phpmyadmin/phpmyadmin/issues/12251

**Comment by DavidMaza** [comment]
The container remains running

```
IMAGE                   COMMAND       CREATED         STATUS           PORTS
phpmyadmin/phpmyadmin   "/run.sh"     2 days ago      Up 30 hours      0.0.0.0:8080->80/tcp

```

**Comment by nijel** [comment]
Can you try updating to latest image? I've made changes in way how sessions are stored and they are now stored in separate volume, what should limit such problems...

**Comment by DavidMaza** [comment]
I had a play around with it. I think it's fixed.

Thanks for fixing it so quickly!

**Comment by mathos** [comment]
I think the issue is still there, Hence David's  "play around," is that I think instead of `-d session.save-path=/sessions` it should be `-d session.save_path=/sessions` with an underscore. Mine's still saving in the `/tmp` directory and still losing the sessions.

**Comment by jmkgreen** [comment]
We have now updated to the latest 4.6.2 with `-d session.save_path=/sessions` in effect within the container.

We are still experiencing the problem :(

**Comment by nijel** [comment]
Do you see session files in the sessions volume?

**Comment by jmkgreen** [comment]
```
/ # ls -l /sessions/
total 464
-rw-------    1 root     root         30212 Jun 13 14:02 sess_03pq7kqr6i35p9plnrqce84lpt5g7uia
-rw-------    1 root     root          1759 Jun 13 13:59 sess_12rcbsfi9c6fdf014pgt99mch6r9uuo5
-rw-------    1 root     root          2363 Jun 13 14:03 sess_2uthrflg1774og8a7chnqbbura6oap3s
-rw-------    1 root     root         24970 Jun 13 17:08 sess_3f1gfb6qoe22dmdes1bq5uvnon1skl8p
-rw-------    1 root     root          1790 Jun 13 14:57 sess_3f9j1b57stqs2211mr2javv1jjosrth6
-rw-------    1 root     root         29137 Jun 13 14:57 sess_4eo82p0mhcrb4dloiob3nlkai1kq4uhm
[ ... ]
```

Pretty good evidence there.

**Comment by nijel** [comment]
It might be different issue in your case then. There is similar question on StackOverflow as well: http://stackoverflow.com/q/37682465/225718

**Comment by chrisburrell** [comment]
Hi

I'm having the same issues. Any ideas how to progress this? Should I raise a different task or re-open?

> / # ls /sessions
> sess_37179chpitnh4j817cvishraqo9oo662 sess_7nmv6mn14r2up0a7iro6rstrk1ie0hk3 sess_aj37jii5rmilkg4hrbogj7sne5mu47q7 sess_djgd1mthfcjtnmp0dopnc77080556ij0 sess_hji44fvi22qo5ttj3qg8c0jnerli2obu sess_mpd7foptekj4qlnbsibr6tvupc9o5llb sess_t6r5qd4lk3r5r88rrp53uqn6mt2b74c9
> sess_5j2ei157sp6c9s29h1sm89i2qbt4smlq sess_a3qnpm2blovsrtbolfdrk4mo8tclmkov sess_b8numk6jf4880n8rhf1lquub6q5mrhbo sess_h0r57kf3511ibaslnko3ip16dqotk359 sess_iqpe08932v435jlbu1p8gj910fvrvldu sess_qefraku2so2hbj8bvhl7j74ek9p725ee sess_vmkmdml0d398qin0q3uc8kmlteub5o8b
> sess_6f478n6rueoesm129g10jnfiug699ofa sess_a7eqnlv89oqfnrn7q5i7qcd40bf8ljga sess_bcq9nl1hesetnthkndo1c488tr5bcckc sess_h5np5a7nef2r1cpiqga4ub75fqoll4q7 sess_k6li7a0kv3u1pn8ftjd5s9vsf5m3n2tv sess_se87r7he79qlpqevbhkrog65vqhfgu8f
> 

The one thing I notice is that Chrome says the path is / (which is accurate), but the 'expires / Max-AGe is in UTC, where we're in the UK. e.g. 2016-09-21T07:52:36.417Z. I'm assuming Chrome would deal with this, given the Z indicates UTC so the cookie has not expired?

Apart from that, I'm a bit stumped. Sometimes I can navigate for a few minutes. Sometimes, it just goes straight away and I can't log back in until I delete the cookies.

I've checked the times and they are correct within a second.

My set-up features an AWS ELB that forwards to a NGinx reverse proxy which forwards to the Docker image, so not sure if that's the issue at all? I'm using the following configuration for that:

I don't configure the docker image at all, except to the PMA_HOST and PMA_ABSOLUTE_URI.

I only have a single instance of phpmyadmin so no cluster or sticky sessions, etc. At the moment, we only have 1 instance of the Nginx server. But I assume it won't be an issue with two of them. Ditto, I assume using an AWS ELB isn't an issue.

I'm running the latest docker hub phpmyadmin/phpmyadmin:4.6.4-1 which I assume is the same as 'latest'.

Any ideas?
Thanks
Chris

**Comment by nsymms** [comment]
Have the same problem here. It's very annoying and makes PMA unusable. After a few minutes of usage, all I get is the login screen. Incorrect passwords will give an error; correct password gives no error. Either way I'm back at the login screen. Sometimes refreshing the web page will get me another few seconds of usage.

I'm linking to a MariaDB container on the docker command line. PMA dockerized version is 4.6.4. I've tried hacking the common.inc.php file to ignore token mismatches, and that helped a little. I think now it works at least until the timeout limit.

I've seen reports on this issue in PMA that date back 3 years. It's a chronic bug that keeps re-appearing.

**Comment by nijel** [comment]
The timezones might be an issue, I have't looked how Docker does configure that. The browser will definitely handle UTC, but the question is whether the time is not already expiring....

**Comment by chrisburrell** [comment]
I'll try this next - could this have something to do with using MariaDB?

**Comment by jmkgreen** [comment]
@nijel docker doesn't know about time zones but the container's c standard library does (GNU libc on most distributions, musl for Alpine).

Most of our containers run with TZ=Europe/London which suffices.

I cannot imagine this would result in being logged out the moment I was successfully logged in (as has happened).

**Comment by chrisburrell** [comment]
@nigel Just tried with the timezone set the London (that's where we are), just in case, and that doesn't work either. After a successful login, sometimes after a few seconds sometimes after a few minutes, we still get redirected to the home page. After that, it's hit and miss whether the login page lets you in at all.

Not sure where to go from there?

**Comment by nijel** [comment]
If the timezone is wrongly set in the container, your session cookie would immediately expire, that's why I had this in mind.

What can happen:

* you loose session cookie (be it expiry, wrong path or something different)
* you loose session data on the server
* the session expires

Can you please check what is the case? On the failed request, please look if it contains `phpMyAdmin` cookie and if there is matching session in the filesystem?

PS: PMA_ABSOLUTE_URI has no effect now, it will work in 4.6.5...

**Comment by nsymms** [comment]
I tried connecting from a machine with time & timezone set to UTC and it worked OK until the first timeout. So,

- Using Chrome or IE from Windows with CDT timezone usually works well until the first timeout. Then I'm stuck at the login screen forever. Clearing cookies / restarting browser sometimes helps, sometimes not. Restarting container and clearing cookies of course works again until first timeout.
- Using Linux with Firefox and UTC timezone works well until first timeout, then random login screens. Often works for 10-30 minutes before bouncing back to login.

Testing cookies on Windows with Fiddler4, while PMA is in "fail" mode (constant login screen), Chrome actually sends 2 "phpMyAdmin" values in the cookie sometimes. It looks like, after a successful login, whenever Chrome requests something from the /js folder on the server, it sends both the new value and another. The extra value appears to be static across failed login attempts. My guess is that this is a very old session value that Chrome sends under certain conditions. Both session values appear in the /sessions folder on the server, and both have very recent timestamps.

I don't completely understand cookie behavior, but I'm pretty sure this isn't normal.

I wish I had time to dive into the code.

**Comment by nijel** [comment]
Probably each of the cookies was set with different path? That could explain it as well as there is probably no order defined and you would randomly end up with valid or invalid session.

Can you check path set for these cookies in your browser? The next step would be to figure out what is setting them...

**Comment by nsymms** [comment]
Yes. As suspected, I have 2 "phpMyAdmin" cookies. One is set for / and the other set for /js/.

**Comment by nsymms** [comment]
The 2nd cookie with path set for /js/ gets set in a response from /js/whitelist.php.

However, we mustn't forget that deleting all cookies still doesn't resolve the issue. I can delete all cookies and I will still bounce back to login screen after 2-3 clicks navigating around PMA.

**Comment by nijel** [comment]
Are you sure it's set /js/whitelist.php? It doesn't do that for me...

**Comment by nsymms** [comment]
It doesn't happen every time. And just now I caught it getting set in /js/get_scripts.js. See attached clip from Fiddler.

![screenshot - 8_24_2016 12_21_29 pm](https://cloud.githubusercontent.com/assets/9939843/17940609/86b0890c-69f5-11e6-97f2-a1555a8554fb.png)

**Comment by nsymms** [comment]
Ok so I deleted and restarted the container, deleted relevant Chrome cookies, and started over. I've been playing with this for a couple of hours and can now easily reproduce the issue. I haven't seen any /js/ cookies this time, so that may be a separate issue.

**Firstly, the workaround**: STAY AWAY from the SQL editors. Use the "Query" tab and put your queries in the window at the bottom. Do NOT use the "inline edit" or "edit" links near the top of the page just under your completed query. ONLY USE THE BOTTOM QUERY WINDOW. And stay away from the "SQL" tab. You will most likely be fine.

To reproduce the failure behavior, all I have to do is go to the SQL tab and enter a query that's more than about 40 characters and contains more than one line. As I am typing in the query, (or after I paste in a query) the browser is doing AJAX type calls back to /lint.php. Sometimes lint.php will send back a new phpMyAdmin cookie with a different value. Sometimes I have to hit the "GO" button and then /import.php will send back that cookie. Either way, the only thing that happens when I hit "GO" is "Token Mismatch" or just nothing. Navigating to another place in PMA will send me back to login.

If, when I hit "GO", the query runs and I get results, all I have to do is edit the query and type a few more characters or blank lines. Then the next "GO" will fail. I realize this isn't exact, but the failure is definitely linked to the SQL editor.

As mentioned above, if I clear cookies and log back into PMA, everything will work great as long as I stay away from the SQL tab.

**Comment by chrisburrell** [comment]
I can concur that I could browse all tables very easily and for a long time but then as soon as I use the SQL editor then I see the same issues. Happy to do more extensive testing on our instance if we need to?

**Comment by nijel** [comment]
I've fixed the wrong path being issued by some files in js folder. Hopefully that will fully resolve this issue.

**Comment by nsymms** [comment]
I've patched my container and this doesn't solve the issue for me. As I mentioned above, I still get logged out even though I haven't seen any cookies with the /js/ path for a while. I don't think the extra cookies are the problem.

So for anyone else who is still having session / logout problems and is looking for an answer, please see my workaround a few posts above. When I get more time I'll do more debugging. I don't think any of the project developers are seeing this issue and that makes it very difficult for them to find and fix.

**Comment by nijel** [comment]
Indeed, if I could reproduce this, it would be much easier to debug the problem ;-). Anyway reopening, as the issue is obviously still not fixed.

**Comment by snadal** [comment]
Same here. I applied  @nijel patch on my container, but no luck.

If it helps, it is very quick to reproduce on our environment. Just launch a new docker container with the default parameters

```
docker run --name myadmin -d --link [my_mysql_container]:db -p 8080:80 phpmyadmin/phpmyadmin
```

After a few clicks (no more than 3-4 of them), you are sent to login screen again. MySQL Version is:

```
root@0cb7929f15db:/# mysql --version
mysql  Ver 14.14 Distrib 5.5.51, for linux2.6 (x86_64) using readline 5.1
```

In our case, this happens even without opening SQL tab. Just some navigation among DB and tables.

Please let me know if we can help you in any testing.

**Comment by nsymms** [comment]
After many hours of debugging today, I have identified the problem. At least on my system. @snadal might have a different issue, but I get his same behavior whenever I don't clear the browser cookies. Just something to try. And apologies for the long post.

**The Problem:**
I've found that the PHP engine (on alpine ??) has some serious cookie memory problems. I'm not a PHP or cookie expert, but it looks like the PHP engine can't grow its cookie memory very fast. Whenever PHP gets a request passed with an increase of more than about 500 characters of cookies (over the previous request), some or all cookies are not processed. That is, they don't make it into the PHP engine in the $_COOKIE variable. And the cookie space inside PHP remains broken until the requests stop passing such a large amount of cookies. I wrote a small PHP program to test this inside the container and it failed exactly as I have described. I even checked using phpinfo() -- once we "fail", only 5-6 pma cookies show up (and not the important ones!). So when the pmaAuth- and pmaUser- cookies don't get processed into PHP space, the auth routines in PMA reset everything. And that gets you back to the login screen. I can clearly see the cookies getting passed to PHP over the wire, but they just don't make it into $_COOKIE[].

**How it happens in PMA:**
The SQL editor in PMA puts your entire query into a cookie and passes it back for lint and sql auto-completion while you're typing. So if I paste in a large query, the cookie space grows too quickly and PHP loses its mind.

Then I tested it by hand-typing. If I slowly type the "long" sql query into PMA. Thus letting the requests get passed to PHP incrementally, I can usually prevent it from failing. I'm thinking the problem must have something to do with malloc() calls or others inside the C library used by PHP.

In truth, the problem could be related to any number of things -- Alpine Linux, the Linux version on the docker host, the docker version, the host's C library versions, who knows what else.

So I'm going to build some of my own containers using a different base until I find one that works.

**Comment by nijel** [comment]
Actually there is no reason to store SQL in cookies - it is not needed at all at server side. So I've changed the code to prefer browser local storage if available in ad51873. I'm not sure if it will be enough, but it definitely reduces pressure on the cookies.

As for the cookie problem, I'd say this is problem of PHP's built in web server...

**Comment by nijel** [comment]
I've prepared move to proper web server + PHP FPM in https://github.com/phpmyadmin/docker/pull/48. This is still not yet fully ready, but probably could be used for testing if it makes things better...

**Comment by nsymms** [comment]
Wow. Thanks for this. Your patch https://github.com/phpmyadmin/phpmyadmin/commit/ad5187383d35c1bace5f3e53afe1449848cbf93d appears to have solved it in my case. I've only hand-typed the patches and tested briefly so far today, but I will do more proper tests and report back.

Cookie usage is stable at around 740 bytes (as reported by Fiddler). Previously it was over 1450 bytes and failing. Maybe you're right about it being a PHP web server issue. I forgot that you're using PHP's built-in web server in the container.

**Comment by chrisburrell** [comment]
Thanks for being so quick! Happy to do some testing too. Is there an easy way to bring in the patch and build it into the docker image?

**Comment by chrisburrell** [comment]
Just tested manually patching the files and it looks like this fixes it for me too!

**Comment by nsymms** [comment]
Probably related to using the built-in PHP web server -- after my 450-byte SQL query executes and I'm at the results page, if I click "Edit" to put me back at the main SQL tab, things break again.

My guess is that the PHP web server can't handle the super long GET request. The entire query in this case (and a couple of others) is passed in the URL. And sometimes it sends me back to the login screen, sometimes it gets me to the SQL tab and the "saved" query isn't there (even though it was passed in the URL).

All this works fine with smaller queries.

I'm going to test this with the newer container in https://github.com/phpmyadmin/docker/pull/48 next.

**Comment by zaverichintan** [comment]
@nijel Thank you the patch. I think instead of cookies, shall we move entire information to local storage?

**Comment by nijel** [comment]
I think it makes sense for information which is never needed on the server side like was in this particular case. The same is probably true for console settings...

**Comment by nijel** [comment]
I've just merged #48, what should eliminate possible issues caused by PHP built in web server. Testing is welcome.

**Comment by nsymms** [comment]
I'm a bit hesitant to post this because I know I tested it yesterday as of https://github.com/phpmyadmin/docker/pull/48/commits/b611c5adde296d26db0cc58589968f6dcfca42c6 and everything worked fine. But it's not going so well today.

I even tried the new container on a fresh AWS instance and connected to it from a different machine than I was using for the other tests. All I get is several INCOMPLETE_CHUNKED_ENCODING errors during the login page load. It happens when the browser requests /js/get_scripts.js.php. I've tried and retried several things and I'm not getting very far with the new container.

I got past the encoding error by changing the exposed IP & port. I have no idea how that made things better, but I tried it three times with the same result. However, after entering a 200-byte SQL query I started getting error 400 - Bad Request. I'm certain this is from the large cookies being passed. I think the cookie patch is in the PMA main project and didn't make it into the container yet.

I hope it's just me having a bad day and things are OK for everyone else. ???

**Comment by nijel** [comment]
I really didn't pay attention to setting limits on both nginx and PHP, hopefully these are now more sane to avoid problems in real world usage.

**Comment by nsymms** [comment]
The patches work well for me.

**Comment by nijel** [comment]
Great, thanks for testing!

**Comment by chrisburrell** [comment]
Hi

Can I just confirm if the dockerhub latest tag has this in? Or should i build directly from here?
Thanks
Chris

**Comment by nijel** [comment]
The latest tag has all the changes on the docker container side, but does not have changes from upcoming 4.6.5 release (reintroduction of absolute URL setting or removal of some cookies). However the cookie removal should not matter with new setup...

**Comment by chrisburrell** [comment]
@nigel thanks for this!

**Comment by chrisburrell** [comment]
Thanks - tested on the latest build too and this works great. Thanks for all the work over the weekend. Much appreciate it.

**Comment by Hassanzadeh-sd** [comment]
you have to set permission for tmp directory `chmod 777 tmp`
